module.exports = [
  {
    id: 1,
    image: '1.jpg',
    name: 'Dr. S. Raja Sabapathy',
    experience: 20,
    department: ['pulmonology'],
    position: 'MD',
    fee: 500,
    time: '1:30PM',
    city: 'bhubaneswar',
    available: 'yes',
  },
  {
    id: 2,
    image: '2.jpg',
    name: 'Dr. S. Raja Sabapathy',
    experience: 20,
    department: ['neurology'],
    position: 'MD',
    fee: 500,
    time: '5:30PM',
    city: 'cuttack',
    available: 'no',
  },
  {
    id: 3,
    image: '3.jpg',
    name: 'Dr. S. Raja Sabapathy',
    experience: 20,
    department: ['neurology', 'lorem, ipsum dolor.'],
    position: 'MD',
    fee: 500,
    time: '2:00PM',
    city: 'bhubaneswar',
    available: 'yes',
  },
  {
    id: 4,
    image: '4.jpg',
    name: 'Dr. S. Raja Sabapathy',
    experience: 20,
    department: ['neurology'],
    position: 'MD',
    fee: 500,
    time: '7:30PM',
    city: 'cuttack',
    available: 'yes',
  },
];
